_target_: src.models.cuti_model.CuTiLitModule

ctrlc:
  MODELS:
    BACKBONE: 'resnet50'
    DILATION: False
    POSITION_EMBEDDING: 'sine'
    MASKS: False
    FROZEN_WEIGHT: None
    USE_STRUCTURE_TENSOR: True

    TRANSFORMER:
      ENC_LAYERS: 6
      DEC_LAYERS: 6
      DIM_FEEDFORWARD: 2048
      HIDDEN_DIM: 256 # 128
      DROPOUT: 0.1
      NHEADS: 8
      NUM_QUERIES: 3
      PRE_NORM: False

ctrlc_checkpoint_path: "/home/kmuvcl/CTRL-C/matterport_log/checkpoint0069.pth"

pos_encoder:
  _target_: src.models.components.position_encoding.PositionEncodingSine1D
  d_model: 256 #512
  max_len: 4096

transformer:
  _target_: src.models.components.transformer.LocalFeatureTransformer
  d_model: 256 #512
  nhead: 8
  layer_types: ["self", "cross", "self", "cross", "self", "cross"]
  attention: "linear"

vptransformer:
  _target_: src.models.components.vp_transformer.VPTransformer
  d_model: 256 #512
  nhead: 8
  layer_types: ["vpcross"]
  attention: "bilinear"

max_num_line: 512 #250
hidden_dim: 256 #512
pool_channels: [32, 16]
pose_regressor_hidden_dim: 256
pose_size: 7

criterion:
#  _target_: src.models.components.losses.GeodesicLoss,src.models.components.losses.L1Loss
  _target_: src.models.components.losses.L1Loss
  weights:
    translation: 10.0
    rotation: 10.0
    vp: 10.0

vp_criterion:
  _target_: src.models.components.vp_loss.VpLoss


test_metric:
  _target_: src.models.components.testfunction.Testcamera
  Reference:
    translation: 1.0
    rotation: 30

matcher:
  _target_: src.models.components.matcher.HungarianMatcher
  

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.1
  patience: 10
